FROM debian:12-slim
RUN apt-get update \
 && apt-get install -y redis-server redis-tools \
 && rm -rf /var/lib/apt/lists/*
COPY conf/redis.conf /etc/redis/redis.conf
VOLUME ["/data"]
CMD ["redis-server", "/etc/redis/redis.conf"]

